replicaCount: 1

image:
  repository: cod8flow-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

ingress:
  enabled: false
  host: ""

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

env:
  DATABASE_URL: jdbc:postgresql://host.docker.internal:5433/cod8flow_db
  DB_USERNAME: cod8flow
  REDIS_HOST: host.docker.internal
  REDIS_PORT: "6379"
  KAFKA_BROKERS: host.docker.internal:9092
  AWS_REGION: ap-south-1
  AWS_S3_BUCKET: cod8flow-bucket
  SPRING_PROFILES_ACTIVE: prod

secrets:
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  DB_PASSWORD: "cod8flow"
  AWS_ACCESS_KEY_ID: "dummy"
  AWS_SECRET_ACCESS_KEY: "dummy"
