apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cod8flow.fullname" . }}-config
  labels:
    {{- include "cod8flow.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  DB_USERNAME: {{ .Values.env.DB_USERNAME | quote }}
  REDIS_HOST: {{ .Values.env.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.env.REDIS_PORT | quote }}
  KAFKA_BROKERS: {{ .Values.env.KAFKA_BROKERS | quote }}
  AWS_REGION: {{ .Values.env.AWS_REGION | quote }}
  AWS_S3_BUCKET: {{ .Values.env.AWS_S3_BUCKET | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
