apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cod8flow.fullname" . }}-secret
  labels:
    {{- include "cod8flow.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.AWS_ACCESS_KEY_ID | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.AWS_SECRET_ACCESS_KEY | b64enc | quote }}
